batting:
  run: 1
  four_bonus: 1
  six_bonus: 2
  duck_penalty: -2

milestones:
  thirty_run_bonus: 4
  fifty_run_bonus: 8
  hundred_run_bonus: 16
  milestone_only_highest: true

bowling:
  wicket: 25
  lbw_bowled_bonus: 8
  maiden_over: 12

bowling_milestones:
  three_wicket_bonus: 4
  four_wicket_bonus: 8
  five_wicket_bonus: 16
  milestone_only_highest: true

fielding:
  catch: 8
  three_catch_bonus: 4
  stumping: 12
  run_out_direct_hit: 12
  run_out_thrower_or_catcher: 6

playing:
  in_starting_xi: 4

strike_rate:
  enabled: true
  min_balls: 10
  ranges:
    - {min: 170, max: 9999, points: 6}
    - {min: 150, max: 169.99, points: 4}
    - {min: 130, max: 149.99, points: 2}
    - {min: 60, max: 70, points: -2}
    - {min: 50, max: 59.99, points: -4}
    - {min: 0, max: 49.99, points: -6}

economy_rate:
  enabled: true
  min_overs: 2
  ranges:
    - {min: 0, max: 5, points: 6}
    - {min: 5.01, max: 6, points: 4}
    - {min: 6.01, max: 7, points: 2}
    - {min: 10, max: 11, points: -2}
    - {min: 11.01, max: 12, points: -4}
    - {min: 12.01, max: 999, points: -6}
